/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_ruk_tutorials_natives_Natives */

#ifndef _Included_net_avc_video_cutter_natives_Natives
#define _Included_net_avc_video_cutter_natives_Natives
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_ruk_tutorials_natives_Natives
 * Method:    takePics
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_net_avc_video_cutter_natives_Natives_takePics
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
