################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
../libavcodec/4xm.c \
../libavcodec/8bps.c \
../libavcodec/8svx.c \
../libavcodec/aac_ac3_parser.c \
../libavcodec/aac_adtstoasc_bsf.c \
../libavcodec/aac_parser.c \
../libavcodec/aac_tablegen.c \
../libavcodec/aaccoder.c \
../libavcodec/aacdec.c \
../libavcodec/aacenc.c \
../libavcodec/aacps.c \
../libavcodec/aacps_tablegen.c \
../libavcodec/aacpsdata.c \
../libavcodec/aacpsy.c \
../libavcodec/aacsbr.c \
../libavcodec/aactab.c \
../libavcodec/aandcttab.c \
../libavcodec/aasc.c \
../libavcodec/ac3.c \
../libavcodec/ac3_parser.c \
../libavcodec/ac3dec.c \
../libavcodec/ac3dec_data.c \
../libavcodec/ac3enc.c \
../libavcodec/ac3tab.c \
../libavcodec/acelp_filters.c \
../libavcodec/acelp_pitch_delay.c \
../libavcodec/acelp_vectors.c \
../libavcodec/adpcm.c \
../libavcodec/adxdec.c \
../libavcodec/adxenc.c \
../libavcodec/alac.c \
../libavcodec/alacenc.c \
../libavcodec/allcodecs.c \
../libavcodec/alsdec.c \
../libavcodec/amrnbdec.c \
../libavcodec/anm.c \
../libavcodec/apedec.c \
../libavcodec/api-example.c \
../libavcodec/asv1.c \
../libavcodec/atrac.c \
../libavcodec/atrac1.c \
../libavcodec/atrac3.c \
../libavcodec/audioconvert.c \
../libavcodec/aura.c \
../libavcodec/avfft.c \
../libavcodec/avpacket.c \
../libavcodec/avs.c \
../libavcodec/beosthread.c \
../libavcodec/bethsoftvideo.c \
../libavcodec/bfi.c \
../libavcodec/bgmc.c \
../libavcodec/bink.c \
../libavcodec/binkaudio.c \
../libavcodec/binkidct.c \
../libavcodec/bitstream.c \
../libavcodec/bitstream_filter.c \
../libavcodec/bmp.c \
../libavcodec/bmpenc.c \
../libavcodec/c93.c \
../libavcodec/cabac.c \
../libavcodec/cavs.c \
../libavcodec/cavs_parser.c \
../libavcodec/cavsdec.c \
../libavcodec/cavsdsp.c \
../libavcodec/cbrt_tablegen.c \
../libavcodec/cdgraphics.c \
../libavcodec/celp_filters.c \
../libavcodec/celp_math.c \
../libavcodec/cga_data.c \
../libavcodec/cinepak.c \
../libavcodec/cljr.c \
../libavcodec/cook.c \
../libavcodec/costablegen.c \
../libavcodec/cscd.c \
../libavcodec/cyuv.c \
../libavcodec/dca.c \
../libavcodec/dca_parser.c \
../libavcodec/dcadsp.c \
../libavcodec/dct-test.c \
../libavcodec/dct.c \
../libavcodec/dctref.c \
../libavcodec/dirac.c \
../libavcodec/dirac_parser.c \
../libavcodec/dnxhd_parser.c \
../libavcodec/dnxhddata.c \
../libavcodec/dnxhddec.c \
../libavcodec/dnxhdenc.c \
../libavcodec/dpcm.c \
../libavcodec/dpx.c \
../libavcodec/dsicinav.c \
../libavcodec/dsputil.c \
../libavcodec/dump_extradata_bsf.c \
../libavcodec/dv.c \
../libavcodec/dv_tablegen.c \
../libavcodec/dvbsub.c \
../libavcodec/dvbsub_parser.c \
../libavcodec/dvbsubdec.c \
../libavcodec/dvdata.c \
../libavcodec/dvdsub_parser.c \
../libavcodec/dvdsubdec.c \
../libavcodec/dvdsubenc.c \
../libavcodec/dwt.c \
../libavcodec/dxa.c \
../libavcodec/dxva2.c \
../libavcodec/dxva2_h264.c \
../libavcodec/dxva2_vc1.c \
../libavcodec/eac3dec.c \
../libavcodec/eac3dec_data.c \
../libavcodec/eacmv.c \
../libavcodec/eaidct.c \
../libavcodec/eamad.c \
../libavcodec/eatgq.c \
../libavcodec/eatgv.c \
../libavcodec/eatqi.c \
../libavcodec/elbg.c \
../libavcodec/error_resilience.c \
../libavcodec/escape124.c \
../libavcodec/eval.c \
../libavcodec/faandct.c \
../libavcodec/faanidct.c \
../libavcodec/faxcompr.c \
../libavcodec/fft-test.c \
../libavcodec/fft.c \
../libavcodec/ffv1.c \
../libavcodec/flac.c \
../libavcodec/flacdata.c \
../libavcodec/flacdec.c \
../libavcodec/flacenc.c \
../libavcodec/flashsv.c \
../libavcodec/flashsvenc.c \
../libavcodec/flicvideo.c \
../libavcodec/flvdec.c \
../libavcodec/flvenc.c \
../libavcodec/fraps.c \
../libavcodec/frwu.c \
../libavcodec/g726.c \
../libavcodec/g729dec.c \
../libavcodec/gif.c \
../libavcodec/gifdec.c \
../libavcodec/golomb.c \
../libavcodec/h261.c \
../libavcodec/h261_parser.c \
../libavcodec/h261dec.c \
../libavcodec/h261enc.c \
../libavcodec/h263.c \
../libavcodec/h263_parser.c \
../libavcodec/h263dec.c \
../libavcodec/h264.c \
../libavcodec/h264_cabac.c \
../libavcodec/h264_cavlc.c \
../libavcodec/h264_direct.c \
../libavcodec/h264_loopfilter.c \
../libavcodec/h264_mp4toannexb_bsf.c \
../libavcodec/h264_parser.c \
../libavcodec/h264_ps.c \
../libavcodec/h264_refs.c \
../libavcodec/h264_sei.c \
../libavcodec/h264dsp.c \
../libavcodec/h264dspenc.c \
../libavcodec/h264enc.c \
../libavcodec/h264idct.c \
../libavcodec/h264pred.c \
../libavcodec/huffman.c \
../libavcodec/huffyuv.c \
../libavcodec/idcinvideo.c \
../libavcodec/iff.c \
../libavcodec/iirfilter.c \
../libavcodec/imc.c \
../libavcodec/imgconvert.c \
../libavcodec/imx_dump_header_bsf.c \
../libavcodec/indeo2.c \
../libavcodec/indeo3.c \
../libavcodec/indeo5.c \
../libavcodec/intelh263dec.c \
../libavcodec/interplayvideo.c \
../libavcodec/intrax8.c \
../libavcodec/intrax8dsp.c \
../libavcodec/ituh263dec.c \
../libavcodec/ituh263enc.c \
../libavcodec/ivi_common.c \
../libavcodec/ivi_dsp.c \
../libavcodec/jfdctfst.c \
../libavcodec/jfdctint.c \
../libavcodec/jpegls.c \
../libavcodec/jpeglsdec.c \
../libavcodec/jpeglsenc.c \
../libavcodec/jrevdct.c \
../libavcodec/kgv1dec.c \
../libavcodec/kmvc.c \
../libavcodec/lcldec.c \
../libavcodec/lclenc.c \
../libavcodec/libdirac_libschro.c \
../libavcodec/libdiracdec.c \
../libavcodec/libdiracenc.c \
../libavcodec/libfaac.c \
../libavcodec/libfaad.c \
../libavcodec/libgsm.c \
../libavcodec/libmp3lame.c \
../libavcodec/libopencore-amr.c \
../libavcodec/libopenjpeg.c \
../libavcodec/libschroedinger.c \
../libavcodec/libschroedingerdec.c \
../libavcodec/libschroedingerenc.c \
../libavcodec/libspeexdec.c \
../libavcodec/libtheoraenc.c \
../libavcodec/libvorbis.c \
../libavcodec/libvpxdec.c \
../libavcodec/libvpxenc.c \
../libavcodec/libx264.c \
../libavcodec/libxvid_rc.c \
../libavcodec/libxvidff.c \
../libavcodec/ljpegenc.c \
../libavcodec/loco.c \
../libavcodec/lpc.c \
../libavcodec/lsp.c \
../libavcodec/lzw.c \
../libavcodec/lzwenc.c \
../libavcodec/mace.c \
../libavcodec/mdct.c \
../libavcodec/mdct_tablegen.c \
../libavcodec/mdec.c \
../libavcodec/mimic.c \
../libavcodec/mjpeg.c \
../libavcodec/mjpeg_parser.c \
../libavcodec/mjpega_dump_header_bsf.c \
../libavcodec/mjpegbdec.c \
../libavcodec/mjpegdec.c \
../libavcodec/mjpegenc.c \
../libavcodec/mlp.c \
../libavcodec/mlp_parser.c \
../libavcodec/mlpdec.c \
../libavcodec/mlpdsp.c \
../libavcodec/mmvideo.c \
../libavcodec/motion-test.c \
../libavcodec/motion_est.c \
../libavcodec/motion_est_template.c \
../libavcodec/motionpixels.c \
../libavcodec/motionpixels_tablegen.c \
../libavcodec/movsub_bsf.c \
../libavcodec/mp3_header_compress_bsf.c \
../libavcodec/mp3_header_decompress_bsf.c \
../libavcodec/mpc.c \
../libavcodec/mpc7.c \
../libavcodec/mpc8.c \
../libavcodec/mpeg12.c \
../libavcodec/mpeg12data.c \
../libavcodec/mpeg12enc.c \
../libavcodec/mpeg4audio.c \
../libavcodec/mpeg4video.c \
../libavcodec/mpeg4video_parser.c \
../libavcodec/mpeg4videodec.c \
../libavcodec/mpeg4videoenc.c \
../libavcodec/mpegaudio.c \
../libavcodec/mpegaudio_parser.c \
../libavcodec/mpegaudio_tablegen.c \
../libavcodec/mpegaudiodata.c \
../libavcodec/mpegaudiodec.c \
../libavcodec/mpegaudiodecheader.c \
../libavcodec/mpegaudioenc.c \
../libavcodec/mpegvideo.c \
../libavcodec/mpegvideo_enc.c \
../libavcodec/mpegvideo_parser.c \
../libavcodec/mpegvideo_xvmc.c \
../libavcodec/msmpeg4.c \
../libavcodec/msmpeg4data.c \
../libavcodec/msrle.c \
../libavcodec/msrledec.c \
../libavcodec/msvideo1.c \
../libavcodec/nellymoser.c \
../libavcodec/nellymoserdec.c \
../libavcodec/nellymoserenc.c \
../libavcodec/noise_bsf.c \
../libavcodec/nuv.c \
../libavcodec/opt.c \
../libavcodec/options.c \
../libavcodec/os2thread.c \
../libavcodec/pamenc.c \
../libavcodec/parser.c \
../libavcodec/pcm-mpeg.c \
../libavcodec/pcm.c \
../libavcodec/pcm_tablegen.c \
../libavcodec/pcx.c \
../libavcodec/pcxenc.c \
../libavcodec/pgssubdec.c \
../libavcodec/png.c \
../libavcodec/pngdec.c \
../libavcodec/pngenc.c \
../libavcodec/pnm.c \
../libavcodec/pnm_parser.c \
../libavcodec/pnmdec.c \
../libavcodec/pnmenc.c \
../libavcodec/psymodel.c \
../libavcodec/pthread.c \
../libavcodec/ptx.c \
../libavcodec/qcelpdec.c \
../libavcodec/qdm2.c \
../libavcodec/qdm2_tablegen.c \
../libavcodec/qdrw.c \
../libavcodec/qpeg.c \
../libavcodec/qtrle.c \
../libavcodec/qtrleenc.c \
../libavcodec/r210dec.c \
../libavcodec/ra144.c \
../libavcodec/ra288.c \
../libavcodec/rangecoder.c \
../libavcodec/ratecontrol.c \
../libavcodec/raw.c \
../libavcodec/rawdec.c \
../libavcodec/rawenc.c \
../libavcodec/rdft.c \
../libavcodec/remove_extradata_bsf.c \
../libavcodec/resample.c \
../libavcodec/resample2.c \
../libavcodec/rl2.c \
../libavcodec/rle.c \
../libavcodec/roqaudioenc.c \
../libavcodec/roqvideo.c \
../libavcodec/roqvideodec.c \
../libavcodec/roqvideoenc.c \
../libavcodec/rpza.c \
../libavcodec/rtjpeg.c \
../libavcodec/rv10.c \
../libavcodec/rv10enc.c \
../libavcodec/rv20enc.c \
../libavcodec/rv30.c \
../libavcodec/rv30dsp.c \
../libavcodec/rv34.c \
../libavcodec/rv40.c \
../libavcodec/rv40dsp.c \
../libavcodec/s3tc.c \
../libavcodec/sgidec.c \
../libavcodec/sgienc.c \
../libavcodec/shorten.c \
../libavcodec/simple_idct.c \
../libavcodec/sipr.c \
../libavcodec/sipr16k.c \
../libavcodec/smacker.c \
../libavcodec/smc.c \
../libavcodec/snow.c \
../libavcodec/sonic.c \
../libavcodec/sp5xdec.c \
../libavcodec/sunrast.c \
../libavcodec/svq1.c \
../libavcodec/svq1dec.c \
../libavcodec/svq1enc.c \
../libavcodec/svq3.c \
../libavcodec/synth_filter.c \
../libavcodec/tableprint.c \
../libavcodec/targa.c \
../libavcodec/targaenc.c \
../libavcodec/tiertexseqv.c \
../libavcodec/tiff.c \
../libavcodec/tiffenc.c \
../libavcodec/tmv.c \
../libavcodec/truemotion1.c \
../libavcodec/truemotion2.c \
../libavcodec/truespeech.c \
../libavcodec/tscc.c \
../libavcodec/tta.c \
../libavcodec/twinvq.c \
../libavcodec/txd.c \
../libavcodec/ulti.c \
../libavcodec/utils.c \
../libavcodec/v210dec.c \
../libavcodec/v210enc.c \
../libavcodec/v210x.c \
../libavcodec/vaapi.c \
../libavcodec/vaapi_h264.c \
../libavcodec/vaapi_mpeg2.c \
../libavcodec/vaapi_mpeg4.c \
../libavcodec/vaapi_vc1.c \
../libavcodec/vb.c \
../libavcodec/vc1.c \
../libavcodec/vc1_parser.c \
../libavcodec/vc1data.c \
../libavcodec/vc1dec.c \
../libavcodec/vc1dsp.c \
../libavcodec/vcr1.c \
../libavcodec/vdpau.c \
../libavcodec/vmdav.c \
../libavcodec/vmnc.c \
../libavcodec/vorbis.c \
../libavcodec/vorbis_data.c \
../libavcodec/vorbis_dec.c \
../libavcodec/vorbis_enc.c \
../libavcodec/vp3.c \
../libavcodec/vp3_parser.c \
../libavcodec/vp3dsp.c \
../libavcodec/vp5.c \
../libavcodec/vp56.c \
../libavcodec/vp56data.c \
../libavcodec/vp56dsp.c \
../libavcodec/vp6.c \
../libavcodec/vp6dsp.c \
../libavcodec/vqavideo.c \
../libavcodec/w32thread.c \
../libavcodec/wavpack.c \
../libavcodec/wma.c \
../libavcodec/wmadec.c \
../libavcodec/wmaenc.c \
../libavcodec/wmaprodec.c \
../libavcodec/wmavoice.c \
../libavcodec/wmv2.c \
../libavcodec/wmv2dec.c \
../libavcodec/wmv2enc.c \
../libavcodec/wnv1.c \
../libavcodec/ws-snd1.c \
../libavcodec/xan.c \
../libavcodec/xiph.c \
../libavcodec/xl.c \
../libavcodec/xsubdec.c \
../libavcodec/xsubenc.c \
../libavcodec/yop.c \
../libavcodec/zmbv.c \
../libavcodec/zmbvenc.c 

OBJS += \
./libavcodec/4xm.o \
./libavcodec/8bps.o \
./libavcodec/8svx.o \
./libavcodec/aac_ac3_parser.o \
./libavcodec/aac_adtstoasc_bsf.o \
./libavcodec/aac_parser.o \
./libavcodec/aac_tablegen.o \
./libavcodec/aaccoder.o \
./libavcodec/aacdec.o \
./libavcodec/aacenc.o \
./libavcodec/aacps.o \
./libavcodec/aacps_tablegen.o \
./libavcodec/aacpsdata.o \
./libavcodec/aacpsy.o \
./libavcodec/aacsbr.o \
./libavcodec/aactab.o \
./libavcodec/aandcttab.o \
./libavcodec/aasc.o \
./libavcodec/ac3.o \
./libavcodec/ac3_parser.o \
./libavcodec/ac3dec.o \
./libavcodec/ac3dec_data.o \
./libavcodec/ac3enc.o \
./libavcodec/ac3tab.o \
./libavcodec/acelp_filters.o \
./libavcodec/acelp_pitch_delay.o \
./libavcodec/acelp_vectors.o \
./libavcodec/adpcm.o \
./libavcodec/adxdec.o \
./libavcodec/adxenc.o \
./libavcodec/alac.o \
./libavcodec/alacenc.o \
./libavcodec/allcodecs.o \
./libavcodec/alsdec.o \
./libavcodec/amrnbdec.o \
./libavcodec/anm.o \
./libavcodec/apedec.o \
./libavcodec/api-example.o \
./libavcodec/asv1.o \
./libavcodec/atrac.o \
./libavcodec/atrac1.o \
./libavcodec/atrac3.o \
./libavcodec/audioconvert.o \
./libavcodec/aura.o \
./libavcodec/avfft.o \
./libavcodec/avpacket.o \
./libavcodec/avs.o \
./libavcodec/beosthread.o \
./libavcodec/bethsoftvideo.o \
./libavcodec/bfi.o \
./libavcodec/bgmc.o \
./libavcodec/bink.o \
./libavcodec/binkaudio.o \
./libavcodec/binkidct.o \
./libavcodec/bitstream.o \
./libavcodec/bitstream_filter.o \
./libavcodec/bmp.o \
./libavcodec/bmpenc.o \
./libavcodec/c93.o \
./libavcodec/cabac.o \
./libavcodec/cavs.o \
./libavcodec/cavs_parser.o \
./libavcodec/cavsdec.o \
./libavcodec/cavsdsp.o \
./libavcodec/cbrt_tablegen.o \
./libavcodec/cdgraphics.o \
./libavcodec/celp_filters.o \
./libavcodec/celp_math.o \
./libavcodec/cga_data.o \
./libavcodec/cinepak.o \
./libavcodec/cljr.o \
./libavcodec/cook.o \
./libavcodec/costablegen.o \
./libavcodec/cscd.o \
./libavcodec/cyuv.o \
./libavcodec/dca.o \
./libavcodec/dca_parser.o \
./libavcodec/dcadsp.o \
./libavcodec/dct-test.o \
./libavcodec/dct.o \
./libavcodec/dctref.o \
./libavcodec/dirac.o \
./libavcodec/dirac_parser.o \
./libavcodec/dnxhd_parser.o \
./libavcodec/dnxhddata.o \
./libavcodec/dnxhddec.o \
./libavcodec/dnxhdenc.o \
./libavcodec/dpcm.o \
./libavcodec/dpx.o \
./libavcodec/dsicinav.o \
./libavcodec/dsputil.o \
./libavcodec/dump_extradata_bsf.o \
./libavcodec/dv.o \
./libavcodec/dv_tablegen.o \
./libavcodec/dvbsub.o \
./libavcodec/dvbsub_parser.o \
./libavcodec/dvbsubdec.o \
./libavcodec/dvdata.o \
./libavcodec/dvdsub_parser.o \
./libavcodec/dvdsubdec.o \
./libavcodec/dvdsubenc.o \
./libavcodec/dwt.o \
./libavcodec/dxa.o \
./libavcodec/dxva2.o \
./libavcodec/dxva2_h264.o \
./libavcodec/dxva2_vc1.o \
./libavcodec/eac3dec.o \
./libavcodec/eac3dec_data.o \
./libavcodec/eacmv.o \
./libavcodec/eaidct.o \
./libavcodec/eamad.o \
./libavcodec/eatgq.o \
./libavcodec/eatgv.o \
./libavcodec/eatqi.o \
./libavcodec/elbg.o \
./libavcodec/error_resilience.o \
./libavcodec/escape124.o \
./libavcodec/eval.o \
./libavcodec/faandct.o \
./libavcodec/faanidct.o \
./libavcodec/faxcompr.o \
./libavcodec/fft-test.o \
./libavcodec/fft.o \
./libavcodec/ffv1.o \
./libavcodec/flac.o \
./libavcodec/flacdata.o \
./libavcodec/flacdec.o \
./libavcodec/flacenc.o \
./libavcodec/flashsv.o \
./libavcodec/flashsvenc.o \
./libavcodec/flicvideo.o \
./libavcodec/flvdec.o \
./libavcodec/flvenc.o \
./libavcodec/fraps.o \
./libavcodec/frwu.o \
./libavcodec/g726.o \
./libavcodec/g729dec.o \
./libavcodec/gif.o \
./libavcodec/gifdec.o \
./libavcodec/golomb.o \
./libavcodec/h261.o \
./libavcodec/h261_parser.o \
./libavcodec/h261dec.o \
./libavcodec/h261enc.o \
./libavcodec/h263.o \
./libavcodec/h263_parser.o \
./libavcodec/h263dec.o \
./libavcodec/h264.o \
./libavcodec/h264_cabac.o \
./libavcodec/h264_cavlc.o \
./libavcodec/h264_direct.o \
./libavcodec/h264_loopfilter.o \
./libavcodec/h264_mp4toannexb_bsf.o \
./libavcodec/h264_parser.o \
./libavcodec/h264_ps.o \
./libavcodec/h264_refs.o \
./libavcodec/h264_sei.o \
./libavcodec/h264dsp.o \
./libavcodec/h264dspenc.o \
./libavcodec/h264enc.o \
./libavcodec/h264idct.o \
./libavcodec/h264pred.o \
./libavcodec/huffman.o \
./libavcodec/huffyuv.o \
./libavcodec/idcinvideo.o \
./libavcodec/iff.o \
./libavcodec/iirfilter.o \
./libavcodec/imc.o \
./libavcodec/imgconvert.o \
./libavcodec/imx_dump_header_bsf.o \
./libavcodec/indeo2.o \
./libavcodec/indeo3.o \
./libavcodec/indeo5.o \
./libavcodec/intelh263dec.o \
./libavcodec/interplayvideo.o \
./libavcodec/intrax8.o \
./libavcodec/intrax8dsp.o \
./libavcodec/ituh263dec.o \
./libavcodec/ituh263enc.o \
./libavcodec/ivi_common.o \
./libavcodec/ivi_dsp.o \
./libavcodec/jfdctfst.o \
./libavcodec/jfdctint.o \
./libavcodec/jpegls.o \
./libavcodec/jpeglsdec.o \
./libavcodec/jpeglsenc.o \
./libavcodec/jrevdct.o \
./libavcodec/kgv1dec.o \
./libavcodec/kmvc.o \
./libavcodec/lcldec.o \
./libavcodec/lclenc.o \
./libavcodec/libdirac_libschro.o \
./libavcodec/libdiracdec.o \
./libavcodec/libdiracenc.o \
./libavcodec/libfaac.o \
./libavcodec/libfaad.o \
./libavcodec/libgsm.o \
./libavcodec/libmp3lame.o \
./libavcodec/libopencore-amr.o \
./libavcodec/libopenjpeg.o \
./libavcodec/libschroedinger.o \
./libavcodec/libschroedingerdec.o \
./libavcodec/libschroedingerenc.o \
./libavcodec/libspeexdec.o \
./libavcodec/libtheoraenc.o \
./libavcodec/libvorbis.o \
./libavcodec/libvpxdec.o \
./libavcodec/libvpxenc.o \
./libavcodec/libx264.o \
./libavcodec/libxvid_rc.o \
./libavcodec/libxvidff.o \
./libavcodec/ljpegenc.o \
./libavcodec/loco.o \
./libavcodec/lpc.o \
./libavcodec/lsp.o \
./libavcodec/lzw.o \
./libavcodec/lzwenc.o \
./libavcodec/mace.o \
./libavcodec/mdct.o \
./libavcodec/mdct_tablegen.o \
./libavcodec/mdec.o \
./libavcodec/mimic.o \
./libavcodec/mjpeg.o \
./libavcodec/mjpeg_parser.o \
./libavcodec/mjpega_dump_header_bsf.o \
./libavcodec/mjpegbdec.o \
./libavcodec/mjpegdec.o \
./libavcodec/mjpegenc.o \
./libavcodec/mlp.o \
./libavcodec/mlp_parser.o \
./libavcodec/mlpdec.o \
./libavcodec/mlpdsp.o \
./libavcodec/mmvideo.o \
./libavcodec/motion-test.o \
./libavcodec/motion_est.o \
./libavcodec/motion_est_template.o \
./libavcodec/motionpixels.o \
./libavcodec/motionpixels_tablegen.o \
./libavcodec/movsub_bsf.o \
./libavcodec/mp3_header_compress_bsf.o \
./libavcodec/mp3_header_decompress_bsf.o \
./libavcodec/mpc.o \
./libavcodec/mpc7.o \
./libavcodec/mpc8.o \
./libavcodec/mpeg12.o \
./libavcodec/mpeg12data.o \
./libavcodec/mpeg12enc.o \
./libavcodec/mpeg4audio.o \
./libavcodec/mpeg4video.o \
./libavcodec/mpeg4video_parser.o \
./libavcodec/mpeg4videodec.o \
./libavcodec/mpeg4videoenc.o \
./libavcodec/mpegaudio.o \
./libavcodec/mpegaudio_parser.o \
./libavcodec/mpegaudio_tablegen.o \
./libavcodec/mpegaudiodata.o \
./libavcodec/mpegaudiodec.o \
./libavcodec/mpegaudiodecheader.o \
./libavcodec/mpegaudioenc.o \
./libavcodec/mpegvideo.o \
./libavcodec/mpegvideo_enc.o \
./libavcodec/mpegvideo_parser.o \
./libavcodec/mpegvideo_xvmc.o \
./libavcodec/msmpeg4.o \
./libavcodec/msmpeg4data.o \
./libavcodec/msrle.o \
./libavcodec/msrledec.o \
./libavcodec/msvideo1.o \
./libavcodec/nellymoser.o \
./libavcodec/nellymoserdec.o \
./libavcodec/nellymoserenc.o \
./libavcodec/noise_bsf.o \
./libavcodec/nuv.o \
./libavcodec/opt.o \
./libavcodec/options.o \
./libavcodec/os2thread.o \
./libavcodec/pamenc.o \
./libavcodec/parser.o \
./libavcodec/pcm-mpeg.o \
./libavcodec/pcm.o \
./libavcodec/pcm_tablegen.o \
./libavcodec/pcx.o \
./libavcodec/pcxenc.o \
./libavcodec/pgssubdec.o \
./libavcodec/png.o \
./libavcodec/pngdec.o \
./libavcodec/pngenc.o \
./libavcodec/pnm.o \
./libavcodec/pnm_parser.o \
./libavcodec/pnmdec.o \
./libavcodec/pnmenc.o \
./libavcodec/psymodel.o \
./libavcodec/pthread.o \
./libavcodec/ptx.o \
./libavcodec/qcelpdec.o \
./libavcodec/qdm2.o \
./libavcodec/qdm2_tablegen.o \
./libavcodec/qdrw.o \
./libavcodec/qpeg.o \
./libavcodec/qtrle.o \
./libavcodec/qtrleenc.o \
./libavcodec/r210dec.o \
./libavcodec/ra144.o \
./libavcodec/ra288.o \
./libavcodec/rangecoder.o \
./libavcodec/ratecontrol.o \
./libavcodec/raw.o \
./libavcodec/rawdec.o \
./libavcodec/rawenc.o \
./libavcodec/rdft.o \
./libavcodec/remove_extradata_bsf.o \
./libavcodec/resample.o \
./libavcodec/resample2.o \
./libavcodec/rl2.o \
./libavcodec/rle.o \
./libavcodec/roqaudioenc.o \
./libavcodec/roqvideo.o \
./libavcodec/roqvideodec.o \
./libavcodec/roqvideoenc.o \
./libavcodec/rpza.o \
./libavcodec/rtjpeg.o \
./libavcodec/rv10.o \
./libavcodec/rv10enc.o \
./libavcodec/rv20enc.o \
./libavcodec/rv30.o \
./libavcodec/rv30dsp.o \
./libavcodec/rv34.o \
./libavcodec/rv40.o \
./libavcodec/rv40dsp.o \
./libavcodec/s3tc.o \
./libavcodec/sgidec.o \
./libavcodec/sgienc.o \
./libavcodec/shorten.o \
./libavcodec/simple_idct.o \
./libavcodec/sipr.o \
./libavcodec/sipr16k.o \
./libavcodec/smacker.o \
./libavcodec/smc.o \
./libavcodec/snow.o \
./libavcodec/sonic.o \
./libavcodec/sp5xdec.o \
./libavcodec/sunrast.o \
./libavcodec/svq1.o \
./libavcodec/svq1dec.o \
./libavcodec/svq1enc.o \
./libavcodec/svq3.o \
./libavcodec/synth_filter.o \
./libavcodec/tableprint.o \
./libavcodec/targa.o \
./libavcodec/targaenc.o \
./libavcodec/tiertexseqv.o \
./libavcodec/tiff.o \
./libavcodec/tiffenc.o \
./libavcodec/tmv.o \
./libavcodec/truemotion1.o \
./libavcodec/truemotion2.o \
./libavcodec/truespeech.o \
./libavcodec/tscc.o \
./libavcodec/tta.o \
./libavcodec/twinvq.o \
./libavcodec/txd.o \
./libavcodec/ulti.o \
./libavcodec/utils.o \
./libavcodec/v210dec.o \
./libavcodec/v210enc.o \
./libavcodec/v210x.o \
./libavcodec/vaapi.o \
./libavcodec/vaapi_h264.o \
./libavcodec/vaapi_mpeg2.o \
./libavcodec/vaapi_mpeg4.o \
./libavcodec/vaapi_vc1.o \
./libavcodec/vb.o \
./libavcodec/vc1.o \
./libavcodec/vc1_parser.o \
./libavcodec/vc1data.o \
./libavcodec/vc1dec.o \
./libavcodec/vc1dsp.o \
./libavcodec/vcr1.o \
./libavcodec/vdpau.o \
./libavcodec/vmdav.o \
./libavcodec/vmnc.o \
./libavcodec/vorbis.o \
./libavcodec/vorbis_data.o \
./libavcodec/vorbis_dec.o \
./libavcodec/vorbis_enc.o \
./libavcodec/vp3.o \
./libavcodec/vp3_parser.o \
./libavcodec/vp3dsp.o \
./libavcodec/vp5.o \
./libavcodec/vp56.o \
./libavcodec/vp56data.o \
./libavcodec/vp56dsp.o \
./libavcodec/vp6.o \
./libavcodec/vp6dsp.o \
./libavcodec/vqavideo.o \
./libavcodec/w32thread.o \
./libavcodec/wavpack.o \
./libavcodec/wma.o \
./libavcodec/wmadec.o \
./libavcodec/wmaenc.o \
./libavcodec/wmaprodec.o \
./libavcodec/wmavoice.o \
./libavcodec/wmv2.o \
./libavcodec/wmv2dec.o \
./libavcodec/wmv2enc.o \
./libavcodec/wnv1.o \
./libavcodec/ws-snd1.o \
./libavcodec/xan.o \
./libavcodec/xiph.o \
./libavcodec/xl.o \
./libavcodec/xsubdec.o \
./libavcodec/xsubenc.o \
./libavcodec/yop.o \
./libavcodec/zmbv.o \
./libavcodec/zmbvenc.o 

C_DEPS += \
./libavcodec/4xm.d \
./libavcodec/8bps.d \
./libavcodec/8svx.d \
./libavcodec/aac_ac3_parser.d \
./libavcodec/aac_adtstoasc_bsf.d \
./libavcodec/aac_parser.d \
./libavcodec/aac_tablegen.d \
./libavcodec/aaccoder.d \
./libavcodec/aacdec.d \
./libavcodec/aacenc.d \
./libavcodec/aacps.d \
./libavcodec/aacps_tablegen.d \
./libavcodec/aacpsdata.d \
./libavcodec/aacpsy.d \
./libavcodec/aacsbr.d \
./libavcodec/aactab.d \
./libavcodec/aandcttab.d \
./libavcodec/aasc.d \
./libavcodec/ac3.d \
./libavcodec/ac3_parser.d \
./libavcodec/ac3dec.d \
./libavcodec/ac3dec_data.d \
./libavcodec/ac3enc.d \
./libavcodec/ac3tab.d \
./libavcodec/acelp_filters.d \
./libavcodec/acelp_pitch_delay.d \
./libavcodec/acelp_vectors.d \
./libavcodec/adpcm.d \
./libavcodec/adxdec.d \
./libavcodec/adxenc.d \
./libavcodec/alac.d \
./libavcodec/alacenc.d \
./libavcodec/allcodecs.d \
./libavcodec/alsdec.d \
./libavcodec/amrnbdec.d \
./libavcodec/anm.d \
./libavcodec/apedec.d \
./libavcodec/api-example.d \
./libavcodec/asv1.d \
./libavcodec/atrac.d \
./libavcodec/atrac1.d \
./libavcodec/atrac3.d \
./libavcodec/audioconvert.d \
./libavcodec/aura.d \
./libavcodec/avfft.d \
./libavcodec/avpacket.d \
./libavcodec/avs.d \
./libavcodec/beosthread.d \
./libavcodec/bethsoftvideo.d \
./libavcodec/bfi.d \
./libavcodec/bgmc.d \
./libavcodec/bink.d \
./libavcodec/binkaudio.d \
./libavcodec/binkidct.d \
./libavcodec/bitstream.d \
./libavcodec/bitstream_filter.d \
./libavcodec/bmp.d \
./libavcodec/bmpenc.d \
./libavcodec/c93.d \
./libavcodec/cabac.d \
./libavcodec/cavs.d \
./libavcodec/cavs_parser.d \
./libavcodec/cavsdec.d \
./libavcodec/cavsdsp.d \
./libavcodec/cbrt_tablegen.d \
./libavcodec/cdgraphics.d \
./libavcodec/celp_filters.d \
./libavcodec/celp_math.d \
./libavcodec/cga_data.d \
./libavcodec/cinepak.d \
./libavcodec/cljr.d \
./libavcodec/cook.d \
./libavcodec/costablegen.d \
./libavcodec/cscd.d \
./libavcodec/cyuv.d \
./libavcodec/dca.d \
./libavcodec/dca_parser.d \
./libavcodec/dcadsp.d \
./libavcodec/dct-test.d \
./libavcodec/dct.d \
./libavcodec/dctref.d \
./libavcodec/dirac.d \
./libavcodec/dirac_parser.d \
./libavcodec/dnxhd_parser.d \
./libavcodec/dnxhddata.d \
./libavcodec/dnxhddec.d \
./libavcodec/dnxhdenc.d \
./libavcodec/dpcm.d \
./libavcodec/dpx.d \
./libavcodec/dsicinav.d \
./libavcodec/dsputil.d \
./libavcodec/dump_extradata_bsf.d \
./libavcodec/dv.d \
./libavcodec/dv_tablegen.d \
./libavcodec/dvbsub.d \
./libavcodec/dvbsub_parser.d \
./libavcodec/dvbsubdec.d \
./libavcodec/dvdata.d \
./libavcodec/dvdsub_parser.d \
./libavcodec/dvdsubdec.d \
./libavcodec/dvdsubenc.d \
./libavcodec/dwt.d \
./libavcodec/dxa.d \
./libavcodec/dxva2.d \
./libavcodec/dxva2_h264.d \
./libavcodec/dxva2_vc1.d \
./libavcodec/eac3dec.d \
./libavcodec/eac3dec_data.d \
./libavcodec/eacmv.d \
./libavcodec/eaidct.d \
./libavcodec/eamad.d \
./libavcodec/eatgq.d \
./libavcodec/eatgv.d \
./libavcodec/eatqi.d \
./libavcodec/elbg.d \
./libavcodec/error_resilience.d \
./libavcodec/escape124.d \
./libavcodec/eval.d \
./libavcodec/faandct.d \
./libavcodec/faanidct.d \
./libavcodec/faxcompr.d \
./libavcodec/fft-test.d \
./libavcodec/fft.d \
./libavcodec/ffv1.d \
./libavcodec/flac.d \
./libavcodec/flacdata.d \
./libavcodec/flacdec.d \
./libavcodec/flacenc.d \
./libavcodec/flashsv.d \
./libavcodec/flashsvenc.d \
./libavcodec/flicvideo.d \
./libavcodec/flvdec.d \
./libavcodec/flvenc.d \
./libavcodec/fraps.d \
./libavcodec/frwu.d \
./libavcodec/g726.d \
./libavcodec/g729dec.d \
./libavcodec/gif.d \
./libavcodec/gifdec.d \
./libavcodec/golomb.d \
./libavcodec/h261.d \
./libavcodec/h261_parser.d \
./libavcodec/h261dec.d \
./libavcodec/h261enc.d \
./libavcodec/h263.d \
./libavcodec/h263_parser.d \
./libavcodec/h263dec.d \
./libavcodec/h264.d \
./libavcodec/h264_cabac.d \
./libavcodec/h264_cavlc.d \
./libavcodec/h264_direct.d \
./libavcodec/h264_loopfilter.d \
./libavcodec/h264_mp4toannexb_bsf.d \
./libavcodec/h264_parser.d \
./libavcodec/h264_ps.d \
./libavcodec/h264_refs.d \
./libavcodec/h264_sei.d \
./libavcodec/h264dsp.d \
./libavcodec/h264dspenc.d \
./libavcodec/h264enc.d \
./libavcodec/h264idct.d \
./libavcodec/h264pred.d \
./libavcodec/huffman.d \
./libavcodec/huffyuv.d \
./libavcodec/idcinvideo.d \
./libavcodec/iff.d \
./libavcodec/iirfilter.d \
./libavcodec/imc.d \
./libavcodec/imgconvert.d \
./libavcodec/imx_dump_header_bsf.d \
./libavcodec/indeo2.d \
./libavcodec/indeo3.d \
./libavcodec/indeo5.d \
./libavcodec/intelh263dec.d \
./libavcodec/interplayvideo.d \
./libavcodec/intrax8.d \
./libavcodec/intrax8dsp.d \
./libavcodec/ituh263dec.d \
./libavcodec/ituh263enc.d \
./libavcodec/ivi_common.d \
./libavcodec/ivi_dsp.d \
./libavcodec/jfdctfst.d \
./libavcodec/jfdctint.d \
./libavcodec/jpegls.d \
./libavcodec/jpeglsdec.d \
./libavcodec/jpeglsenc.d \
./libavcodec/jrevdct.d \
./libavcodec/kgv1dec.d \
./libavcodec/kmvc.d \
./libavcodec/lcldec.d \
./libavcodec/lclenc.d \
./libavcodec/libdirac_libschro.d \
./libavcodec/libdiracdec.d \
./libavcodec/libdiracenc.d \
./libavcodec/libfaac.d \
./libavcodec/libfaad.d \
./libavcodec/libgsm.d \
./libavcodec/libmp3lame.d \
./libavcodec/libopencore-amr.d \
./libavcodec/libopenjpeg.d \
./libavcodec/libschroedinger.d \
./libavcodec/libschroedingerdec.d \
./libavcodec/libschroedingerenc.d \
./libavcodec/libspeexdec.d \
./libavcodec/libtheoraenc.d \
./libavcodec/libvorbis.d \
./libavcodec/libvpxdec.d \
./libavcodec/libvpxenc.d \
./libavcodec/libx264.d \
./libavcodec/libxvid_rc.d \
./libavcodec/libxvidff.d \
./libavcodec/ljpegenc.d \
./libavcodec/loco.d \
./libavcodec/lpc.d \
./libavcodec/lsp.d \
./libavcodec/lzw.d \
./libavcodec/lzwenc.d \
./libavcodec/mace.d \
./libavcodec/mdct.d \
./libavcodec/mdct_tablegen.d \
./libavcodec/mdec.d \
./libavcodec/mimic.d \
./libavcodec/mjpeg.d \
./libavcodec/mjpeg_parser.d \
./libavcodec/mjpega_dump_header_bsf.d \
./libavcodec/mjpegbdec.d \
./libavcodec/mjpegdec.d \
./libavcodec/mjpegenc.d \
./libavcodec/mlp.d \
./libavcodec/mlp_parser.d \
./libavcodec/mlpdec.d \
./libavcodec/mlpdsp.d \
./libavcodec/mmvideo.d \
./libavcodec/motion-test.d \
./libavcodec/motion_est.d \
./libavcodec/motion_est_template.d \
./libavcodec/motionpixels.d \
./libavcodec/motionpixels_tablegen.d \
./libavcodec/movsub_bsf.d \
./libavcodec/mp3_header_compress_bsf.d \
./libavcodec/mp3_header_decompress_bsf.d \
./libavcodec/mpc.d \
./libavcodec/mpc7.d \
./libavcodec/mpc8.d \
./libavcodec/mpeg12.d \
./libavcodec/mpeg12data.d \
./libavcodec/mpeg12enc.d \
./libavcodec/mpeg4audio.d \
./libavcodec/mpeg4video.d \
./libavcodec/mpeg4video_parser.d \
./libavcodec/mpeg4videodec.d \
./libavcodec/mpeg4videoenc.d \
./libavcodec/mpegaudio.d \
./libavcodec/mpegaudio_parser.d \
./libavcodec/mpegaudio_tablegen.d \
./libavcodec/mpegaudiodata.d \
./libavcodec/mpegaudiodec.d \
./libavcodec/mpegaudiodecheader.d \
./libavcodec/mpegaudioenc.d \
./libavcodec/mpegvideo.d \
./libavcodec/mpegvideo_enc.d \
./libavcodec/mpegvideo_parser.d \
./libavcodec/mpegvideo_xvmc.d \
./libavcodec/msmpeg4.d \
./libavcodec/msmpeg4data.d \
./libavcodec/msrle.d \
./libavcodec/msrledec.d \
./libavcodec/msvideo1.d \
./libavcodec/nellymoser.d \
./libavcodec/nellymoserdec.d \
./libavcodec/nellymoserenc.d \
./libavcodec/noise_bsf.d \
./libavcodec/nuv.d \
./libavcodec/opt.d \
./libavcodec/options.d \
./libavcodec/os2thread.d \
./libavcodec/pamenc.d \
./libavcodec/parser.d \
./libavcodec/pcm-mpeg.d \
./libavcodec/pcm.d \
./libavcodec/pcm_tablegen.d \
./libavcodec/pcx.d \
./libavcodec/pcxenc.d \
./libavcodec/pgssubdec.d \
./libavcodec/png.d \
./libavcodec/pngdec.d \
./libavcodec/pngenc.d \
./libavcodec/pnm.d \
./libavcodec/pnm_parser.d \
./libavcodec/pnmdec.d \
./libavcodec/pnmenc.d \
./libavcodec/psymodel.d \
./libavcodec/pthread.d \
./libavcodec/ptx.d \
./libavcodec/qcelpdec.d \
./libavcodec/qdm2.d \
./libavcodec/qdm2_tablegen.d \
./libavcodec/qdrw.d \
./libavcodec/qpeg.d \
./libavcodec/qtrle.d \
./libavcodec/qtrleenc.d \
./libavcodec/r210dec.d \
./libavcodec/ra144.d \
./libavcodec/ra288.d \
./libavcodec/rangecoder.d \
./libavcodec/ratecontrol.d \
./libavcodec/raw.d \
./libavcodec/rawdec.d \
./libavcodec/rawenc.d \
./libavcodec/rdft.d \
./libavcodec/remove_extradata_bsf.d \
./libavcodec/resample.d \
./libavcodec/resample2.d \
./libavcodec/rl2.d \
./libavcodec/rle.d \
./libavcodec/roqaudioenc.d \
./libavcodec/roqvideo.d \
./libavcodec/roqvideodec.d \
./libavcodec/roqvideoenc.d \
./libavcodec/rpza.d \
./libavcodec/rtjpeg.d \
./libavcodec/rv10.d \
./libavcodec/rv10enc.d \
./libavcodec/rv20enc.d \
./libavcodec/rv30.d \
./libavcodec/rv30dsp.d \
./libavcodec/rv34.d \
./libavcodec/rv40.d \
./libavcodec/rv40dsp.d \
./libavcodec/s3tc.d \
./libavcodec/sgidec.d \
./libavcodec/sgienc.d \
./libavcodec/shorten.d \
./libavcodec/simple_idct.d \
./libavcodec/sipr.d \
./libavcodec/sipr16k.d \
./libavcodec/smacker.d \
./libavcodec/smc.d \
./libavcodec/snow.d \
./libavcodec/sonic.d \
./libavcodec/sp5xdec.d \
./libavcodec/sunrast.d \
./libavcodec/svq1.d \
./libavcodec/svq1dec.d \
./libavcodec/svq1enc.d \
./libavcodec/svq3.d \
./libavcodec/synth_filter.d \
./libavcodec/tableprint.d \
./libavcodec/targa.d \
./libavcodec/targaenc.d \
./libavcodec/tiertexseqv.d \
./libavcodec/tiff.d \
./libavcodec/tiffenc.d \
./libavcodec/tmv.d \
./libavcodec/truemotion1.d \
./libavcodec/truemotion2.d \
./libavcodec/truespeech.d \
./libavcodec/tscc.d \
./libavcodec/tta.d \
./libavcodec/twinvq.d \
./libavcodec/txd.d \
./libavcodec/ulti.d \
./libavcodec/utils.d \
./libavcodec/v210dec.d \
./libavcodec/v210enc.d \
./libavcodec/v210x.d \
./libavcodec/vaapi.d \
./libavcodec/vaapi_h264.d \
./libavcodec/vaapi_mpeg2.d \
./libavcodec/vaapi_mpeg4.d \
./libavcodec/vaapi_vc1.d \
./libavcodec/vb.d \
./libavcodec/vc1.d \
./libavcodec/vc1_parser.d \
./libavcodec/vc1data.d \
./libavcodec/vc1dec.d \
./libavcodec/vc1dsp.d \
./libavcodec/vcr1.d \
./libavcodec/vdpau.d \
./libavcodec/vmdav.d \
./libavcodec/vmnc.d \
./libavcodec/vorbis.d \
./libavcodec/vorbis_data.d \
./libavcodec/vorbis_dec.d \
./libavcodec/vorbis_enc.d \
./libavcodec/vp3.d \
./libavcodec/vp3_parser.d \
./libavcodec/vp3dsp.d \
./libavcodec/vp5.d \
./libavcodec/vp56.d \
./libavcodec/vp56data.d \
./libavcodec/vp56dsp.d \
./libavcodec/vp6.d \
./libavcodec/vp6dsp.d \
./libavcodec/vqavideo.d \
./libavcodec/w32thread.d \
./libavcodec/wavpack.d \
./libavcodec/wma.d \
./libavcodec/wmadec.d \
./libavcodec/wmaenc.d \
./libavcodec/wmaprodec.d \
./libavcodec/wmavoice.d \
./libavcodec/wmv2.d \
./libavcodec/wmv2dec.d \
./libavcodec/wmv2enc.d \
./libavcodec/wnv1.d \
./libavcodec/ws-snd1.d \
./libavcodec/xan.d \
./libavcodec/xiph.d \
./libavcodec/xl.d \
./libavcodec/xsubdec.d \
./libavcodec/xsubenc.d \
./libavcodec/yop.d \
./libavcodec/zmbv.d \
./libavcodec/zmbvenc.d 


# Each subdirectory must supply rules for building sources it contributes
libavcodec/%.o: ../libavcodec/%.c
	@echo 'Building file: $<'
	@echo 'Invoking: GCC C Compiler'
	gcc -I/home/uday/mount/android-ndk-r4b/build/platforms/android-8/arch-arm/usr/include -I/home/uday/mount/ffmpeg-lib/include -O0 -g3 -Wall -c -fmessage-length=0 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@:%.o=%.d)" -o"$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '


