################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
../libavformat/4xm.c \
../libavformat/adtsenc.c \
../libavformat/aea.c \
../libavformat/aiffdec.c \
../libavformat/aiffenc.c \
../libavformat/allformats.c \
../libavformat/amr.c \
../libavformat/anm.c \
../libavformat/apc.c \
../libavformat/ape.c \
../libavformat/apetag.c \
../libavformat/asf.c \
../libavformat/asfcrypt.c \
../libavformat/asfdec.c \
../libavformat/asfenc.c \
../libavformat/assdec.c \
../libavformat/assenc.c \
../libavformat/au.c \
../libavformat/audiointerleave.c \
../libavformat/avc.c \
../libavformat/avi.c \
../libavformat/avidec.c \
../libavformat/avienc.c \
../libavformat/avio.c \
../libavformat/aviobuf.c \
../libavformat/avisynth.c \
../libavformat/avlanguage.c \
../libavformat/avs.c \
../libavformat/bethsoftvid.c \
../libavformat/bfi.c \
../libavformat/bink.c \
../libavformat/c93.c \
../libavformat/caf.c \
../libavformat/cafdec.c \
../libavformat/cdg.c \
../libavformat/concat.c \
../libavformat/crcenc.c \
../libavformat/cutils.c \
../libavformat/daud.c \
../libavformat/dsicin.c \
../libavformat/dv.c \
../libavformat/dvenc.c \
../libavformat/dxa.c \
../libavformat/eacdata.c \
../libavformat/electronicarts.c \
../libavformat/ffmdec.c \
../libavformat/ffmenc.c \
../libavformat/file.c \
../libavformat/filmstripdec.c \
../libavformat/filmstripenc.c \
../libavformat/flacdec.c \
../libavformat/flacenc.c \
../libavformat/flacenc_header.c \
../libavformat/flic.c \
../libavformat/flvdec.c \
../libavformat/flvenc.c \
../libavformat/framecrcenc.c \
../libavformat/gif.c \
../libavformat/gopher.c \
../libavformat/gxf.c \
../libavformat/gxfenc.c \
../libavformat/http.c \
../libavformat/httpauth.c \
../libavformat/id3v1.c \
../libavformat/id3v2.c \
../libavformat/idcin.c \
../libavformat/idroq.c \
../libavformat/iff.c \
../libavformat/img2.c \
../libavformat/ipmovie.c \
../libavformat/isom.c \
../libavformat/iss.c \
../libavformat/iv8.c \
../libavformat/libnut.c \
../libavformat/librtmp.c \
../libavformat/lmlm4.c \
../libavformat/matroska.c \
../libavformat/matroskadec.c \
../libavformat/matroskaenc.c \
../libavformat/metadata.c \
../libavformat/metadata_compat.c \
../libavformat/mm.c \
../libavformat/mmf.c \
../libavformat/mov.c \
../libavformat/movenc.c \
../libavformat/movenchint.c \
../libavformat/mp3.c \
../libavformat/mpc.c \
../libavformat/mpc8.c \
../libavformat/mpeg.c \
../libavformat/mpegenc.c \
../libavformat/mpegts.c \
../libavformat/mpegtsenc.c \
../libavformat/mpjpeg.c \
../libavformat/msnwc_tcp.c \
../libavformat/mtv.c \
../libavformat/mvi.c \
../libavformat/mxf.c \
../libavformat/mxfdec.c \
../libavformat/mxfenc.c \
../libavformat/ncdec.c \
../libavformat/nsvdec.c \
../libavformat/nut.c \
../libavformat/nutdec.c \
../libavformat/nutenc.c \
../libavformat/nuv.c \
../libavformat/oggdec.c \
../libavformat/oggenc.c \
../libavformat/oggparsedirac.c \
../libavformat/oggparseflac.c \
../libavformat/oggparseogm.c \
../libavformat/oggparseskeleton.c \
../libavformat/oggparsespeex.c \
../libavformat/oggparsetheora.c \
../libavformat/oggparsevorbis.c \
../libavformat/oma.c \
../libavformat/options.c \
../libavformat/os_support.c \
../libavformat/output-example.c \
../libavformat/psxstr.c \
../libavformat/pva.c \
../libavformat/qcp.c \
../libavformat/r3d.c \
../libavformat/raw.c \
../libavformat/rdt.c \
../libavformat/riff.c \
../libavformat/rl2.c \
../libavformat/rm.c \
../libavformat/rmdec.c \
../libavformat/rmenc.c \
../libavformat/rpl.c \
../libavformat/rtmppkt.c \
../libavformat/rtmpproto.c \
../libavformat/rtp.c \
../libavformat/rtpdec.c \
../libavformat/rtpdec_amr.c \
../libavformat/rtpdec_asf.c \
../libavformat/rtpdec_h263.c \
../libavformat/rtpdec_h264.c \
../libavformat/rtpdec_xiph.c \
../libavformat/rtpenc.c \
../libavformat/rtpenc_aac.c \
../libavformat/rtpenc_amr.c \
../libavformat/rtpenc_h263.c \
../libavformat/rtpenc_h264.c \
../libavformat/rtpenc_mpv.c \
../libavformat/rtpproto.c \
../libavformat/rtsp.c \
../libavformat/rtspenc.c \
../libavformat/sdp.c \
../libavformat/seek.c \
../libavformat/segafilm.c \
../libavformat/sierravmd.c \
../libavformat/siff.c \
../libavformat/smacker.c \
../libavformat/sol.c \
../libavformat/soxdec.c \
../libavformat/soxenc.c \
../libavformat/spdif.c \
../libavformat/swfdec.c \
../libavformat/swfenc.c \
../libavformat/tcp.c \
../libavformat/thp.c \
../libavformat/tiertexseq.c \
../libavformat/timefilter.c \
../libavformat/tmv.c \
../libavformat/tta.c \
../libavformat/txd.c \
../libavformat/udp.c \
../libavformat/utils.c \
../libavformat/vc1test.c \
../libavformat/vc1testenc.c \
../libavformat/voc.c \
../libavformat/vocdec.c \
../libavformat/vocenc.c \
../libavformat/vorbiscomment.c \
../libavformat/vqf.c \
../libavformat/wav.c \
../libavformat/wc3movie.c \
../libavformat/westwood.c \
../libavformat/wv.c \
../libavformat/xa.c \
../libavformat/yop.c \
../libavformat/yuv4mpeg.c 

OBJS += \
./libavformat/4xm.o \
./libavformat/adtsenc.o \
./libavformat/aea.o \
./libavformat/aiffdec.o \
./libavformat/aiffenc.o \
./libavformat/allformats.o \
./libavformat/amr.o \
./libavformat/anm.o \
./libavformat/apc.o \
./libavformat/ape.o \
./libavformat/apetag.o \
./libavformat/asf.o \
./libavformat/asfcrypt.o \
./libavformat/asfdec.o \
./libavformat/asfenc.o \
./libavformat/assdec.o \
./libavformat/assenc.o \
./libavformat/au.o \
./libavformat/audiointerleave.o \
./libavformat/avc.o \
./libavformat/avi.o \
./libavformat/avidec.o \
./libavformat/avienc.o \
./libavformat/avio.o \
./libavformat/aviobuf.o \
./libavformat/avisynth.o \
./libavformat/avlanguage.o \
./libavformat/avs.o \
./libavformat/bethsoftvid.o \
./libavformat/bfi.o \
./libavformat/bink.o \
./libavformat/c93.o \
./libavformat/caf.o \
./libavformat/cafdec.o \
./libavformat/cdg.o \
./libavformat/concat.o \
./libavformat/crcenc.o \
./libavformat/cutils.o \
./libavformat/daud.o \
./libavformat/dsicin.o \
./libavformat/dv.o \
./libavformat/dvenc.o \
./libavformat/dxa.o \
./libavformat/eacdata.o \
./libavformat/electronicarts.o \
./libavformat/ffmdec.o \
./libavformat/ffmenc.o \
./libavformat/file.o \
./libavformat/filmstripdec.o \
./libavformat/filmstripenc.o \
./libavformat/flacdec.o \
./libavformat/flacenc.o \
./libavformat/flacenc_header.o \
./libavformat/flic.o \
./libavformat/flvdec.o \
./libavformat/flvenc.o \
./libavformat/framecrcenc.o \
./libavformat/gif.o \
./libavformat/gopher.o \
./libavformat/gxf.o \
./libavformat/gxfenc.o \
./libavformat/http.o \
./libavformat/httpauth.o \
./libavformat/id3v1.o \
./libavformat/id3v2.o \
./libavformat/idcin.o \
./libavformat/idroq.o \
./libavformat/iff.o \
./libavformat/img2.o \
./libavformat/ipmovie.o \
./libavformat/isom.o \
./libavformat/iss.o \
./libavformat/iv8.o \
./libavformat/libnut.o \
./libavformat/librtmp.o \
./libavformat/lmlm4.o \
./libavformat/matroska.o \
./libavformat/matroskadec.o \
./libavformat/matroskaenc.o \
./libavformat/metadata.o \
./libavformat/metadata_compat.o \
./libavformat/mm.o \
./libavformat/mmf.o \
./libavformat/mov.o \
./libavformat/movenc.o \
./libavformat/movenchint.o \
./libavformat/mp3.o \
./libavformat/mpc.o \
./libavformat/mpc8.o \
./libavformat/mpeg.o \
./libavformat/mpegenc.o \
./libavformat/mpegts.o \
./libavformat/mpegtsenc.o \
./libavformat/mpjpeg.o \
./libavformat/msnwc_tcp.o \
./libavformat/mtv.o \
./libavformat/mvi.o \
./libavformat/mxf.o \
./libavformat/mxfdec.o \
./libavformat/mxfenc.o \
./libavformat/ncdec.o \
./libavformat/nsvdec.o \
./libavformat/nut.o \
./libavformat/nutdec.o \
./libavformat/nutenc.o \
./libavformat/nuv.o \
./libavformat/oggdec.o \
./libavformat/oggenc.o \
./libavformat/oggparsedirac.o \
./libavformat/oggparseflac.o \
./libavformat/oggparseogm.o \
./libavformat/oggparseskeleton.o \
./libavformat/oggparsespeex.o \
./libavformat/oggparsetheora.o \
./libavformat/oggparsevorbis.o \
./libavformat/oma.o \
./libavformat/options.o \
./libavformat/os_support.o \
./libavformat/output-example.o \
./libavformat/psxstr.o \
./libavformat/pva.o \
./libavformat/qcp.o \
./libavformat/r3d.o \
./libavformat/raw.o \
./libavformat/rdt.o \
./libavformat/riff.o \
./libavformat/rl2.o \
./libavformat/rm.o \
./libavformat/rmdec.o \
./libavformat/rmenc.o \
./libavformat/rpl.o \
./libavformat/rtmppkt.o \
./libavformat/rtmpproto.o \
./libavformat/rtp.o \
./libavformat/rtpdec.o \
./libavformat/rtpdec_amr.o \
./libavformat/rtpdec_asf.o \
./libavformat/rtpdec_h263.o \
./libavformat/rtpdec_h264.o \
./libavformat/rtpdec_xiph.o \
./libavformat/rtpenc.o \
./libavformat/rtpenc_aac.o \
./libavformat/rtpenc_amr.o \
./libavformat/rtpenc_h263.o \
./libavformat/rtpenc_h264.o \
./libavformat/rtpenc_mpv.o \
./libavformat/rtpproto.o \
./libavformat/rtsp.o \
./libavformat/rtspenc.o \
./libavformat/sdp.o \
./libavformat/seek.o \
./libavformat/segafilm.o \
./libavformat/sierravmd.o \
./libavformat/siff.o \
./libavformat/smacker.o \
./libavformat/sol.o \
./libavformat/soxdec.o \
./libavformat/soxenc.o \
./libavformat/spdif.o \
./libavformat/swfdec.o \
./libavformat/swfenc.o \
./libavformat/tcp.o \
./libavformat/thp.o \
./libavformat/tiertexseq.o \
./libavformat/timefilter.o \
./libavformat/tmv.o \
./libavformat/tta.o \
./libavformat/txd.o \
./libavformat/udp.o \
./libavformat/utils.o \
./libavformat/vc1test.o \
./libavformat/vc1testenc.o \
./libavformat/voc.o \
./libavformat/vocdec.o \
./libavformat/vocenc.o \
./libavformat/vorbiscomment.o \
./libavformat/vqf.o \
./libavformat/wav.o \
./libavformat/wc3movie.o \
./libavformat/westwood.o \
./libavformat/wv.o \
./libavformat/xa.o \
./libavformat/yop.o \
./libavformat/yuv4mpeg.o 

C_DEPS += \
./libavformat/4xm.d \
./libavformat/adtsenc.d \
./libavformat/aea.d \
./libavformat/aiffdec.d \
./libavformat/aiffenc.d \
./libavformat/allformats.d \
./libavformat/amr.d \
./libavformat/anm.d \
./libavformat/apc.d \
./libavformat/ape.d \
./libavformat/apetag.d \
./libavformat/asf.d \
./libavformat/asfcrypt.d \
./libavformat/asfdec.d \
./libavformat/asfenc.d \
./libavformat/assdec.d \
./libavformat/assenc.d \
./libavformat/au.d \
./libavformat/audiointerleave.d \
./libavformat/avc.d \
./libavformat/avi.d \
./libavformat/avidec.d \
./libavformat/avienc.d \
./libavformat/avio.d \
./libavformat/aviobuf.d \
./libavformat/avisynth.d \
./libavformat/avlanguage.d \
./libavformat/avs.d \
./libavformat/bethsoftvid.d \
./libavformat/bfi.d \
./libavformat/bink.d \
./libavformat/c93.d \
./libavformat/caf.d \
./libavformat/cafdec.d \
./libavformat/cdg.d \
./libavformat/concat.d \
./libavformat/crcenc.d \
./libavformat/cutils.d \
./libavformat/daud.d \
./libavformat/dsicin.d \
./libavformat/dv.d \
./libavformat/dvenc.d \
./libavformat/dxa.d \
./libavformat/eacdata.d \
./libavformat/electronicarts.d \
./libavformat/ffmdec.d \
./libavformat/ffmenc.d \
./libavformat/file.d \
./libavformat/filmstripdec.d \
./libavformat/filmstripenc.d \
./libavformat/flacdec.d \
./libavformat/flacenc.d \
./libavformat/flacenc_header.d \
./libavformat/flic.d \
./libavformat/flvdec.d \
./libavformat/flvenc.d \
./libavformat/framecrcenc.d \
./libavformat/gif.d \
./libavformat/gopher.d \
./libavformat/gxf.d \
./libavformat/gxfenc.d \
./libavformat/http.d \
./libavformat/httpauth.d \
./libavformat/id3v1.d \
./libavformat/id3v2.d \
./libavformat/idcin.d \
./libavformat/idroq.d \
./libavformat/iff.d \
./libavformat/img2.d \
./libavformat/ipmovie.d \
./libavformat/isom.d \
./libavformat/iss.d \
./libavformat/iv8.d \
./libavformat/libnut.d \
./libavformat/librtmp.d \
./libavformat/lmlm4.d \
./libavformat/matroska.d \
./libavformat/matroskadec.d \
./libavformat/matroskaenc.d \
./libavformat/metadata.d \
./libavformat/metadata_compat.d \
./libavformat/mm.d \
./libavformat/mmf.d \
./libavformat/mov.d \
./libavformat/movenc.d \
./libavformat/movenchint.d \
./libavformat/mp3.d \
./libavformat/mpc.d \
./libavformat/mpc8.d \
./libavformat/mpeg.d \
./libavformat/mpegenc.d \
./libavformat/mpegts.d \
./libavformat/mpegtsenc.d \
./libavformat/mpjpeg.d \
./libavformat/msnwc_tcp.d \
./libavformat/mtv.d \
./libavformat/mvi.d \
./libavformat/mxf.d \
./libavformat/mxfdec.d \
./libavformat/mxfenc.d \
./libavformat/ncdec.d \
./libavformat/nsvdec.d \
./libavformat/nut.d \
./libavformat/nutdec.d \
./libavformat/nutenc.d \
./libavformat/nuv.d \
./libavformat/oggdec.d \
./libavformat/oggenc.d \
./libavformat/oggparsedirac.d \
./libavformat/oggparseflac.d \
./libavformat/oggparseogm.d \
./libavformat/oggparseskeleton.d \
./libavformat/oggparsespeex.d \
./libavformat/oggparsetheora.d \
./libavformat/oggparsevorbis.d \
./libavformat/oma.d \
./libavformat/options.d \
./libavformat/os_support.d \
./libavformat/output-example.d \
./libavformat/psxstr.d \
./libavformat/pva.d \
./libavformat/qcp.d \
./libavformat/r3d.d \
./libavformat/raw.d \
./libavformat/rdt.d \
./libavformat/riff.d \
./libavformat/rl2.d \
./libavformat/rm.d \
./libavformat/rmdec.d \
./libavformat/rmenc.d \
./libavformat/rpl.d \
./libavformat/rtmppkt.d \
./libavformat/rtmpproto.d \
./libavformat/rtp.d \
./libavformat/rtpdec.d \
./libavformat/rtpdec_amr.d \
./libavformat/rtpdec_asf.d \
./libavformat/rtpdec_h263.d \
./libavformat/rtpdec_h264.d \
./libavformat/rtpdec_xiph.d \
./libavformat/rtpenc.d \
./libavformat/rtpenc_aac.d \
./libavformat/rtpenc_amr.d \
./libavformat/rtpenc_h263.d \
./libavformat/rtpenc_h264.d \
./libavformat/rtpenc_mpv.d \
./libavformat/rtpproto.d \
./libavformat/rtsp.d \
./libavformat/rtspenc.d \
./libavformat/sdp.d \
./libavformat/seek.d \
./libavformat/segafilm.d \
./libavformat/sierravmd.d \
./libavformat/siff.d \
./libavformat/smacker.d \
./libavformat/sol.d \
./libavformat/soxdec.d \
./libavformat/soxenc.d \
./libavformat/spdif.d \
./libavformat/swfdec.d \
./libavformat/swfenc.d \
./libavformat/tcp.d \
./libavformat/thp.d \
./libavformat/tiertexseq.d \
./libavformat/timefilter.d \
./libavformat/tmv.d \
./libavformat/tta.d \
./libavformat/txd.d \
./libavformat/udp.d \
./libavformat/utils.d \
./libavformat/vc1test.d \
./libavformat/vc1testenc.d \
./libavformat/voc.d \
./libavformat/vocdec.d \
./libavformat/vocenc.d \
./libavformat/vorbiscomment.d \
./libavformat/vqf.d \
./libavformat/wav.d \
./libavformat/wc3movie.d \
./libavformat/westwood.d \
./libavformat/wv.d \
./libavformat/xa.d \
./libavformat/yop.d \
./libavformat/yuv4mpeg.d 


# Each subdirectory must supply rules for building sources it contributes
libavformat/%.o: ../libavformat/%.c
	@echo 'Building file: $<'
	@echo 'Invoking: GCC C Compiler'
	gcc -I/home/uday/mount/android-ndk-r4b/build/platforms/android-8/arch-arm/usr/include -I/home/uday/mount/ffmpeg-lib/include -O0 -g3 -Wall -c -fmessage-length=0 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@:%.o=%.d)" -o"$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '


